name: checks

on:
  push:
    branches: [master]
  pull_request: {}
  repository_dispatch:
    types: [custom-event]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run linter
      run: yarn lint

  tests:
    strategy:
      matrix:
        package:
          - core
          - plugin-hardhat

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run tests
      run: yarn --cwd "packages/${{matrix.package}}" run test

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run coverage
      run: yarn coverage

    - uses: codecov/codecov-action@v5

  update-foundry-submodule:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run triggered job
      run: echo "Running tests from ${{ github.event.client_payload }}"