name: checks

on:
  push:
    branches: [master]
  pull_request: {}
  repository_dispatch:
    types: [update-foundry-submodule-docs]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run linter
      run: yarn lint

  tests:
    strategy:
      matrix:
        package:
          - core
          - plugin-hardhat

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run tests
      run: yarn --cwd "packages/${{matrix.package}}" run test

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Run coverage
      run: yarn coverage

    - uses: codecov/codecov-action@v5

  update-foundry-submodule-docs:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true 

    - name: Set up environment
      uses: ./.github/actions/setup

    - name: Update submodule
      run: |
        cd submodules/openzeppelin-foundry-upgrades
        git fetch origin main
        git reset --hard origin/main

    - name: Regenerate docs
      run: yarn docs

    - name: Check for changes in docs/
      id: check_changes
      run: |
        [ -n "$(git diff --name-only HEAD -- docs/)" ] && echo "SHOULD_COMMIT_DOC_UPDATE=true" >> $GITHUB_ENV || true

    - name: Commit and push changes
      if: env.SHOULD_COMMIT_DOC_UPDATE == 'true'
      run: |
        git add docs/
        git commit -m "[CI] Update Foundry Upgrades plugin docs"

    - name: Create a Pull Request for docs changes
      if: env.SHOULD_COMMIT_DOC_UPDATE == 'true'
      run: |
        gh pr create --title "[CI] Update Foundry Upgrades plugin docs" --body "[CI] This PR updates the docs for the Foundry Upgrades plugin" --base main --head $GITHUB_REF